name: Deploy Static Content to GitHub Pages

on:
    pull_request:
        branches: ['main']
    push:
        branches: ['main']
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webp

            - name: Install ImageMagick
              uses: mfinelli/setup-imagemagick@v6

            - name: Run image optimization
              run: bash optimize-images.sh
              env:
                  CPU: 2 # GitHub runners have 2 cores

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --immutable

            - name: Build Project
              run: yarn build

            - name: Upload Build Artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './build'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
